version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8.x
  build:
    commands:
      - ant package
  post_build:
    commands:
      - aws s3 cp *.war s3://antbucketforartifacts/
artifacts:
   files:
      - '**/*'
      - appspec.yml
      - application-start-hook.sh
   discard-paths: yes
